PAPER = main
TEX = $(wildcard tex/*.tex)
# BIB = bibliography/ref.bib
BIB = ref.bib
FIGS = $(wildcard pictures/*.pdf pictures/*.png figures/*.pdf figures/*.png graphs/*.pdf graphs/*.png)

.PHONY: all clean

all: $(PAPER).pdf

$(PAPER).pdf: $(TEX) $(BIB) $(FIGS) IEEEtran.cls
	echo $(FIGS)
	pdflatex -shell-escape $(PAPER)
	bibtex $(PAPER)
	pdflatex -shell-escape $(PAPER)
	pdflatex -shell-escape $(PAPER)

clean:
	rm -f *.aux *.bbl *.blg *.log *.out *.cut $(PAPER).pdf
